# Generated by Django 4.1.2 on 2022-11-01 17:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='services',
            field=models.ManyToManyField(to='web.service'),
        ),
        migrations.AddField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='works'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='timeframe',
            field=models.CharField(max_length=100),
        ),
    ]
