# Generated by Django 4.1.2 on 2022-11-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_work_content_work_services_work_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='client',
            field=models.CharField(max_length=50),
        ),
    ]
