# Generated by Django 4.1.2 on 2022-11-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
