# Generated by Django 4.1.2 on 2022-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_newsletter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
