# Generated by Django 4.1.2 on 2022-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_seoproperty_seo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoproperty',
            old_name='name',
            new_name='key_value',
        ),
        migrations.AddField(
            model_name='seoproperty',
            name='key_type',
            field=models.CharField(choices=[('name', 'Name'), ('property', 'Property')], default='name', max_length=20),
        ),
    ]
