# Generated by Django 4.1.2 on 2022-10-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_name_seoproperty_key_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.seo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seo',
            name='seo_tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.seoproperty'),
            preserve_default=False,
        ),
    ]
