# Generated by Django 4.1.2 on 2022-10-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_seo_post_post_post_seo_seo_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='seo',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='seo_tag',
        ),
        migrations.AddField(
            model_name='seo',
            name='seo_tag',
            field=models.ManyToManyField(to='blog.seoproperty'),
        ),
    ]
