# Generated by Django 4.1.2 on 2022-10-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_post_post_seo_remove_seo_seo_tag_seo_seo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.seo'),
        ),
    ]
