# Generated by Django 4.1.2 on 2022-10-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
