# Generated by Django 4.1.2 on 2022-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='', verbose_name='blogs'),
            preserve_default=False,
        ),
    ]
