# Generated by Django 4.1.2 on 2022-10-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.seo'),
        ),
    ]
